'use client'
import { useState } from 'react'
import { Bell, Check, CreditCard, Globe2, Mail, ShieldCheck, UserRound, Users } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Slider } from '@/components/ui/slider'
import { Progress } from '@/components/ui/progress'
export function AccountPage({type}:{type:'billing'|'profile'|'settings'}){if(type==='billing')return <Billing/>;if(type==='profile')return <Profile/>;return <Settings/>}
function Header({eyebrow,title,sub}:{eyebrow:string,title:string,sub:string}){return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{eyebrow}</p><h1 className="mt-2 font-serif text-3xl font-semibold">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{sub}</p></div>}
function Billing(){const [plan,setPlan]=useState('Pro');return <div className="mx-auto flex max-w-6xl flex-col gap-8 p-5 md:p-10"><Header eyebrow="Plan & usage" title="Billing" sub="Manage your plan, credits, and usage history."/><div className="grid gap-4 md:grid-cols-3">{[['Free','$0','For occasional escapes','20 credits'],['Pro','$24','For thoughtful travelers','100 credits'],['Studio','$69','For teams and advisors','350 credits']].map(p=><button key={p[0]} onClick={()=>setPlan(p[0])} className={`flex flex-col items-start gap-4 rounded-lg border p-5 text-left ${plan===p[0]?'border-primary ring-1 ring-primary':'bg-card'}`}><div className="flex w-full justify-between"><h2 className="font-serif text-xl font-semibold">{p[0]}</h2>{plan===p[0]&&<Badge><Check className="size-3"/>Selected</Badge>}</div><p><b className="font-serif text-3xl">{p[1]}</b><span className="text-xs text-muted-foreground"> / month</span></p><p className="text-sm text-muted-foreground">{p[2]}</p><Badge variant="secondary">{p[3]}</Badge></button>)}</div><div className="grid gap-6 lg:grid-cols-[1fr_1.5fr]"><section className="rounded-lg border bg-card p-6"><h2 className="font-serif text-xl font-semibold">Credits this cycle</h2><div className="my-5 flex items-end justify-between"><span className="font-serif text-4xl font-semibold">68</span><span className="text-sm text-muted-foreground">of 100 remaining</span></div><Progress value={68}/><p className="mt-3 text-xs text-muted-foreground">Resets August 1 · Unused credits do not roll over.</p><Button className="mt-6" variant="outline">Buy 25 credits · $8</Button></section><section className="overflow-hidden rounded-lg border bg-card"><div className="border-b p-5"><h2 className="font-serif text-xl font-semibold">Recent usage</h2></div>{[['Jul 12','Itinerary optimizer','−6'],['Jul 11','Restaurant scout','−4'],['Jul 08','Monthly renewal','+100'],['Jul 03','Budget audit','−2']].map(x=><div key={x[0]+x[1]} className="grid grid-cols-[80px_1fr_auto] border-b p-4 text-sm last:border-b-0"><span className="text-muted-foreground">{x[0]}</span><span>{x[1]}</span><b>{x[2]}</b></div>)}</section></div></div>}
function Profile(){const [saved,setSaved]=useState(false);return <div className="mx-auto flex max-w-4xl flex-col gap-8 p-5 md:p-10"><Header eyebrow="Traveler memory" title="Travel profile" sub="Teach Wayfinder how you like to travel. This context follows every trip."/><section className="rounded-lg border bg-card"><div className="border-b p-6"><h2 className="font-serif text-xl font-semibold">Travel style</h2><p className="text-xs text-muted-foreground">Used by agents when making tradeoffs.</p></div><div className="grid gap-6 p-6 md:grid-cols-2"><Field label="Home airport"><Input defaultValue="SFO — San Francisco"/></Field><Field label="Default currency"><Input defaultValue="USD — US Dollar"/></Field><Field label="Daily pace"><Slider defaultValue={[62]} max={100}/><p className="text-xs text-muted-foreground">Balanced, with room to wander</p></Field><Field label="Comfort level"><Slider defaultValue={[72]} max={100}/><p className="text-xs text-muted-foreground">Boutique stays, selective splurges</p></Field><Field label="Food priorities"><Input defaultValue="Local, regional, coffee, tasting menus"/></Field><Field label="Avoid"><Input defaultValue="Overnight buses, large tours, rushed mornings"/></Field><Field label="Mobility notes"><Input placeholder="Add accessibility or mobility preferences"/></Field><Field label="Dietary needs"><Input defaultValue="No restrictions"/></Field></div><div className="flex items-center justify-between border-t p-5"><p className="text-xs text-muted-foreground">Profile applied to 3 active trips</p><Button onClick={()=>setSaved(true)}>{saved?<Check data-icon="inline-start"/>:null}{saved?'Saved':'Save profile'}</Button></div></section></div>}
function Settings(){return <div className="mx-auto flex max-w-4xl flex-col gap-8 p-5 md:p-10"><Header eyebrow="Workspace" title="Settings" sub="Account identity, notifications, and connected services."/><section className="overflow-hidden rounded-lg border bg-card"><Setting icon={UserRound} title="Account details" sub="Name, email, and profile photo"><Button variant="outline" size="sm">Edit</Button></Setting><Setting icon={Bell} title="Agent notifications" sub="Booking windows, completed workflows, and collaborator edits"><Switch defaultChecked/></Setting><Setting icon={Users} title="Collaborators" sub="Jamie Chen and Morgan Lee have trip access"><Button variant="outline" size="sm">Manage</Button></Setting><Setting icon={Globe2} title="Locale & currency" sub="English (US) · USD"><Button variant="outline" size="sm">Change</Button></Setting><Setting icon={ShieldCheck} title="Privacy & data" sub="Exports, trip history, and agent memory"><Button variant="outline" size="sm">Review</Button></Setting></section><section className="rounded-lg border border-destructive/40 bg-card p-6"><h2 className="font-serif text-xl font-semibold">Account controls</h2><p className="mt-1 text-sm text-muted-foreground">Export your data or permanently close your Wayfinder account.</p><div className="mt-5 flex gap-2"><Button variant="outline">Export data</Button><Button variant="destructive">Delete account</Button></div></section></div>}
function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="flex flex-col gap-2 text-sm font-medium">{label}{children}</label>}
function Setting({icon:Icon,title,sub,children}:{icon:any,title:string,sub:string,children:React.ReactNode}){return <div className="flex items-center gap-4 border-b p-5 last:border-b-0"><span className="flex size-9 items-center justify-center rounded-md bg-secondary"><Icon className="size-4"/></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{title}</p><p className="text-xs text-muted-foreground">{sub}</p></div>{children}</div>}
