'use client'

import Link from 'next/link'
import { ArrowLeft, Bot, CalendarDays, Check, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, ExternalLink, GripVertical, Lock, Map, MapPin, MoreHorizontal, Paperclip, Plane, Send, Share2, Sparkles, Utensils, WandSparkles } from 'lucide-react'
import { useState } from 'react'
import { days, placePins } from '@/lib/wayfinder-data'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Progress } from '@/components/ui/progress'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Textarea } from '@/components/ui/textarea'
import { TripMap } from '@/components/trip-map'

export function TripWorkspace() {
 const [locked,setLocked]=useState<string[]>(['Arrive at Haneda','Sushi Ishiyama'])
 const [booked,setBooked]=useState<string[]>(['Arrive at Haneda','Check in at Trunk Hotel','Sushi Ishiyama'])
 const [messages,setMessages]=useState([{who:'agent',text:'I tightened days 2–4 around neighborhood clusters. You save 48 minutes in transit without dropping any saved places.'},{who:'you',text:'Keep the museum, but make the afternoon less rushed.'},{who:'agent',text:'Done. I moved Koffee Mameya later and added a 50-minute buffer after Nezu Museum. The locked dinner remains unchanged.'}])
 const [draft,setDraft]=useState('')
 const [credits,setCredits]=useState(68)
 const send=()=>{if(!draft.trim())return;setMessages([...messages,{who:'you',text:draft},{who:'agent',text:'I’m comparing this request against your saved preferences and locked items. I’ll propose a safe itinerary update next.'}]);setDraft('')}
 return <div className="flex min-h-[calc(100vh-4rem)] flex-col">
  <header className="flex flex-col gap-3 border-b bg-card px-4 py-3 md:flex-row md:items-center md:justify-between md:px-5"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" render={<Link href="/trips" />}><ArrowLeft /></Button><div><div className="flex items-center gap-2"><h1 className="font-serif text-xl font-semibold">Tokyo in spring</h1><Badge variant="secondary">Planning</Badge></div><p className="text-xs text-muted-foreground">Apr 18–27 · 10 days · 2 travelers · last saved now</p></div></div><div className="flex items-center gap-2"><span className="hidden text-xs text-muted-foreground sm:inline">{credits} credits</span><Dialog><DialogTrigger render={<Button variant="outline" size="sm" />}><WandSparkles data-icon="inline-start" />Run workflow</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Start an agent workflow</DialogTitle><DialogDescription>Choose a focused workflow. Locked items are always preserved.</DialogDescription></DialogHeader><div className="flex flex-col gap-2">{[['Optimize itinerary','6 credits','Rebalance pace, transit, and opening hours.'],['Scout restaurants','4 credits','Find bookable options matching your taste.'],['Monitor bookings','3 credits','Track reservation windows and availability.'],['Budget audit','2 credits','Flag overruns and suggest tradeoffs.'],['Build day trip','5 credits','Create a complete excursion from Tokyo.']].map(w=><button key={w[0]} onClick={()=>setCredits(c=>Math.max(0,c-Number(w[1][0])))} className="flex items-center gap-3 rounded-md border p-3 text-left hover:bg-secondary"><span className="flex size-9 items-center justify-center rounded-md bg-primary/10 text-primary"><Bot className="size-4"/></span><span className="flex-1"><strong className="block text-sm">{w[0]}</strong><span className="text-xs text-muted-foreground">{w[2]}</span></span><Badge variant="outline">{w[1]}</Badge></button>)}</div></DialogContent></Dialog><Button variant="outline" size="sm" render={<Link href="/trips/tokyo-spring/share" />}><Share2 data-icon="inline-start" />Share</Button></div></header>
  <div className="grid flex-1 lg:grid-cols-[250px_minmax(360px,1fr)_280px] 2xl:grid-cols-[330px_minmax(480px,1fr)_380px]">
   <aside className="hidden min-h-0 flex-col border-r bg-card lg:flex"><div className="flex items-center justify-between border-b p-4"><div><h2 className="text-sm font-semibold">Planning agent</h2><p className="text-[11px] text-muted-foreground">Context-aware · 12 artifacts</p></div><span className="flex size-8 items-center justify-center rounded-md bg-primary text-primary-foreground"><Sparkles className="size-4"/></span></div><div className="flex flex-1 flex-col gap-4 overflow-y-auto p-4">{messages.map((m,i)=><div key={i} className={`flex flex-col gap-1 ${m.who==='you'?'items-end':'items-start'}`}><span className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{m.who==='you'?'You':'Wayfinder'}</span><p className={`max-w-[92%] rounded-md p-3 text-xs leading-relaxed ${m.who==='you'?'bg-primary text-primary-foreground':'bg-secondary'}`}>{m.text}</p></div>)}</div><div className="border-t p-3"><Textarea value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing&&e.keyCode!==229){e.preventDefault();send()}}} placeholder="Ask about this trip…" className="min-h-20 resize-none"/><div className="mt-2 flex justify-between"><Button variant="ghost" size="icon"><Paperclip/></Button><Button onClick={send} size="sm"><Send data-icon="inline-end"/>Send</Button></div></div></aside>
   <section className="min-w-0 bg-background"><div className="sticky top-16 z-10 flex items-center justify-between border-b bg-background/95 px-4 py-3 backdrop-blur"><div><h2 className="font-serif text-xl font-semibold">Itinerary</h2><p className="text-xs text-muted-foreground">4 of 10 days · balanced pace</p></div><div className="flex gap-2"><Button size="sm" variant="outline"><CalendarDays data-icon="inline-start"/>Apr 18–27</Button><Button size="icon" variant="ghost"><MoreHorizontal/></Button></div></div><div className="flex flex-col gap-4 p-3 md:p-5">{days.map(day=><article key={day.day} className="overflow-hidden rounded-lg border bg-card"><header className="flex items-center gap-3 border-b bg-secondary/35 p-4"><span className="flex size-10 shrink-0 flex-col items-center justify-center rounded-md bg-primary text-primary-foreground"><span className="text-[9px] uppercase">Day</span><strong className="text-base leading-none">{day.day}</strong></span><div className="min-w-0 flex-1"><h3 className="font-serif text-lg font-semibold">{day.area}</h3><p className="text-xs text-muted-foreground">{day.date} · {day.note}</p></div><Badge variant="outline">Easy pace</Badge></header><div>{day.items.map((item,i)=>{const isLocked=locked.includes(item.title),isBooked=booked.includes(item.title);return <div key={item.title} className="group flex gap-3 border-b p-3 last:border-b-0 md:items-center"><GripVertical className="mt-1 size-4 shrink-0 text-muted-foreground/50 md:mt-0"/><div className="w-11 shrink-0 text-xs font-semibold tabular-nums">{item.time}</div><span className="flex size-8 shrink-0 items-center justify-center rounded-md bg-secondary">{item.type==='Food'?<Utensils className="size-3.5"/>:item.type==='Transit'?<Plane className="size-3.5"/>:<MapPin className="size-3.5"/>}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{item.title}</p>{isBooked&&<Badge className="bg-success text-success-foreground"><Check className="size-3"/>Booked</Badge>}</div><p className="text-xs text-muted-foreground">{item.meta}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={()=>setLocked(isLocked?locked.filter(x=>x!==item.title):[...locked,item.title])} aria-label={isLocked?'Unlock item':'Lock item'}><Lock className={isLocked?'text-primary':'text-muted-foreground'}/></Button><Button size="icon" variant="ghost" onClick={()=>setBooked(isBooked?booked.filter(x=>x!==item.title):[...booked,item.title])} aria-label="Toggle booked"><CheckCircle2 className={isBooked?'text-success':'text-muted-foreground'}/></Button><Button size="icon" variant="ghost"><MoreHorizontal/></Button></div></div>})}</div></article>)}</div></section>
   <aside className="hidden min-h-0 border-l bg-card lg:block"><Tabs defaultValue="map" className="flex h-full flex-col"><TabsList className="m-3 grid grid-cols-4"><TabsTrigger value="map">Map</TabsTrigger><TabsTrigger value="places">Places</TabsTrigger><TabsTrigger value="budget">Budget</TabsTrigger><TabsTrigger value="tasks">Tasks</TabsTrigger></TabsList><TabsContent value="map" className="min-h-0 flex-1"><TripMap/></TabsContent><TabsContent value="places" className="p-4"><PanelTitle title="Place board" sub="28 places · 6 suggested" />{placePins.map(p=><div key={p.n} className="flex items-center gap-3 border-b py-3"><span className="flex size-8 items-center justify-center rounded-md bg-secondary text-xs font-bold">{p.n}</span><div className="flex-1"><p className="text-sm font-medium">{p.name}</p><p className="text-xs text-muted-foreground">{p.kind} · {p.detail}</p></div><Badge variant="outline">Interested</Badge></div>)}</TabsContent><TabsContent value="budget" className="p-4"><PanelTitle title="$4,820 forecast" sub="$180 under your target" /><Progress value={76} className="my-4"/>{[['Flights','$1,420','29%'],['Stays','$1,760','36%'],['Food','$820','17%'],['Transit','$340','7%'],['Activities','$480','10%']].map(x=><div key={x[0]} className="flex items-center justify-between border-b py-3 text-sm"><span>{x[0]}</span><span className="font-medium">{x[1]} <small className="text-muted-foreground">{x[2]}</small></span></div>)}</TabsContent><TabsContent value="tasks" className="p-4"><PanelTitle title="Booking checklist" sub="3 tasks due soon" />{['Reserve Sushi Ishiyama','Buy Ghibli Museum tickets','Choose Hakone ryokan','Activate eSIM'].map((x,i)=><label key={x} className="flex items-start gap-3 border-b py-3"><input type="checkbox" defaultChecked={i===3} className="mt-1 accent-primary"/><span className="flex-1"><span className="block text-sm font-medium">{x}</span><span className="text-xs text-muted-foreground">{i===0?'Due Feb 18':i===1?'Due Mar 10':'Before departure'}</span></span>{i<2&&<Badge variant="outline">High</Badge>}</label>)}</TabsContent></Tabs></aside>
  </div>
 </div>
}
function PanelTitle({title,sub}:{title:string,sub:string}){return <div className="mb-3"><h3 className="font-serif text-xl font-semibold">{title}</h3><p className="text-xs text-muted-foreground">{sub}</p></div>}
